{% set name = "django-mptt-admin" %}
{% set version = "1.0.2" %}
{% set sha256 = "707607cd266f8bae2fd94bc76c3bd4b2f7bc03d9270fd1296d682ca995c551ee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - django
    - django-mptt
    - six

test:
  imports:
    - django_mptt_admin

about:
  home: https://github.com/mbraak/django-mptt-admin
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Django-mptt-admin provides a nice Django Admin interface for Mptt models
  description: Django-mptt-admin provides a nice Django Admin interface for django-mptt models.
  doc_url: https://mbraak.github.io/django-mptt-admin/
  dev_url: https://github.com/mbraak/django-mptt-admin

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
