{% set name = "django-mptt-admin" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9e63d4616ed53c02004ed334073a22d0608c70c90702e5b0e83a564c385f431d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django-mptt

test:
  imports:
    - django_mptt_admin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mbraak/django-mptt-admin
  license: Apache-2.0
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'Django-mptt-admin provides a nice Django Admin interface for Mptt models'
  description: Django-mptt-admin provides a nice Django Admin interface for django-mptt models.
  doc_url: https://mbraak.github.io/django-mptt-admin/
  dev_url: https://github.com/mbraak/django-mptt-admin

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
