{% set name = "django-mptt-admin" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-mptt-admin-{{ version }}.tar.gz
  sha256: b695bfb48ae4a325668cf4949cd738e4a196dac62d9b30bf27afd6fe828034dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django-mptt

test:
  imports:
    - django_mptt_admin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mbraak/django-mptt-admin
  license: Apache-2.0
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'Django-mptt-admin provides a nice Django Admin interface for Mptt models'
  description: Django-mptt-admin provides a nice Django Admin interface for django-mptt models.
  doc_url: https://mbraak.github.io/django-mptt-admin/
  dev_url: https://github.com/mbraak/django-mptt-admin

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
