travis:
  secure:
    BINSTAR_TOKEN: hDhfZIvwaRFiXty3OC6C4jhh7n75azDpbAdDjW2PByRYvRq8vyUNF1lmTUgMIP/DWriGn5jupbMavKpKQUe0plW8JgYiKUBbXtwIzDW4I5jKWHuSBm9wTjKd5rxn0vICBwmjDXdH8AF2NugxfYO3yUhDb9QnzdQ+NZa6lxlgG2npWdZPNkXYFNxwcyXGxym12rIQw2MgeSP1y4rc86JFTvssOWfCTyL9Yt9NmBIG+WAoKbRsOSDaRN+UoF12GwI0oOhZQtJ+Cxvcb3LPqQM37H1MhDJSD1lHjqaGSDgG2D4IXRm65pgA1PA2bgQIIbToAFB3dD4BM+ESj+3ra0O+PdlJavuaheq+DRFpjM+CmMRotYc+m0Z80bH74H6x8Gi8LjWG4lyLmZAMOWEtsDUO1gZ3Zs3sh0gbfMnZ9ZS+nB/8HG24krOsYvUK0m2d9KlzIWMJcCtTVHDoum6fgRMX/tBA1JzeNCFKFpkTuAIbC3DbM2nYG+1FVILy9iW+zZw+bPqvZjtWf9n/o/khYNuXSyjTTPlp0hqq+K5K/Ylluta6rdsHVzZYoEZDVpGeDr+Glbwd3v3ANzEl/IJrFfHO615PiXLGibdF8R/4bDSffcQV+02V+TXvIKMEna/jadpahDZif6Kn8YSVaC/Q6J5K7/5N5HdQXRGISfDKuh0acGk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
