travis:
  secure:
    BINSTAR_TOKEN: sPSQcPZInED8bUigJub9c9g58slzJ7WzX0QweNuLrt0UdunjDzkkk8oIoavOO4ocTnAiY33VzbRrzC2RZuNGopkpHW+ckmohcyBxDsdKD+8qd+FcwB4yYkFvmVl7PYB5jX0tkOlq/MK4w1ur1rFz0H0gt4l2m9LJhihZrIsHoM5zXIisdOb5XUVnC73S+Kh10kLvgnmdNkNdfb09xILTU5BbTHNSxzU2pP5e747ZnrN0Y6vG2++el24t2affbf0KNU3pov5y8l3nWzBiHPnrnu+I21n9WC8TTD9cGzhH2SbQUjb59mOmUGKnZbyF8Gk2fro49sTGe9ehtQd7FshnAfgf89yMRkM3jZMgW8I+g+I7lbozuemcNy77lNffOW/2li5m1JWyDrXhb15EkdxE0R7zzBMnVDJf/CV+h99rl9zSTKhYBcNHSupCS5FiIZGB+wrPMTfPHUeOhRB5IGgD289f6/siRriI3Jn6XERPCWkQothjzEkGdbJYqexBVHXLiVVSnYAOWBTLXaZfloQJ5RWmxqQ86HevDaaqIwbfkqcfBHVhY1KJVebRJJ/lj9u5+K8VmQq6vqCQzuFBNjZGhP5UhDoPvC0vOnshcf8RYEljkYHWxtbUYcLuMNzDjjzqO2SpkVMXGyLWQpRC6sqQ2MLL2SEjUPUlSPPU8bIlof8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
